<?php 
# подключаем классы и собираем данные
if(isset($_REQUEST["section"])){
	$url = explode("/", $_REQUEST["section"]);
} else {
	$url = "";
}

if(!empty($url[2]) && $url[1] !="read") {  } else { if($url[0] == ""){$articles = $this->ListMainPosters(); }}
require_once("controllers/main.controller.php");
$Main = new Main;

require_once('core/MobileDetect.php'); 
$detect = new Mobile_Detect;
if ( $detect->isMobile() ) {
	$_SESSION["TRAFFIC_WAP"] = "true";
	if(isset($_SESSION["mobile_count"])){ unset($_SESSION["mobile_count"]); }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
	<?php if($url[2] != NULL && $url[1] !="read") { 
		$film = $this->setTitle($url[2]);
		if($film["is_single"] == 1){
			echo '<title>'.$film["name"].'</title>';
			echo '<meta name="description" content="'.$film["description"].'" />';
		} else {
			echo '<title>'.$film["name"].'- Сезон '.$film["season_id"].' '.$film["title"].'</title>';
			echo '<meta name="description" content="'.$film["description"].'" />';
		}
	} else {?>
			<title><?php if($_COOKIE['ref'] != 52 && $_COOKIE['ref'] != 462){ echo 'КиноПоиск'; } else { echo 'ВидеоПоиск';} ?> - Главная страница</title>
	<? } ?>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
	<meta name="description" content="description">
	<meta name="keywords" content="keywords">
	<meta name="author" content="author">
	<meta name="robots" content="index, follow">
	<meta name="viewport" content="width=100%; initial-scale=1; maximum-scale=1; minimum-scale=1; user-scalable=no;" />
	<?php if($url[2] != NULL && $url[1] !="read") {?>
		<link rel="stylesheet" href="/templates/css/index.css">
		<link rel="stylesheet" href="/templates/player/css/video.css">
		<script src="/templates/js/jquery-1.7.2.min.js" type="text/javascript"></script>
	<? } else {?>
		<link rel="stylesheet" href="/templates/css/index.css">
	<? } ?>
	<link rel="shortcut icon" href="/templates/img/favicon.ico" type="image/x-icon">
	<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function (d, w, c) {
        (w[c] = w[c] || []).push(function() {
            try {
                w.yaCounter40984969 = new Ya.Metrika({
                    id:40984969,
                    clickmap:true,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true,
                    trackHash:true,
                    ut:"noindex"
                });
            } catch(e) { }
        });

        var n = d.getElementsByTagName("script")[0],
            s = d.createElement("script"),
            f = function () { n.parentNode.insertBefore(s, n); };
        s.type = "text/javascript";
        s.async = true;
        s.src = "https://mc.yandex.ru/metrika/watch.js";

        if (w.opera == "[object Opera]") {
            d.addEventListener("DOMContentLoaded", f, false);
        } else { f(); }
    })(document, window, "yandex_metrika_callbacks");
</script>
<noscript><div><img src="https://mc.yandex.ru/watch/40984969?ut=noindex" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</head>
<body class="page-video">

<?php if($url[2] != NULL && $url[1] !="read") { ?>
	<span class="i-top-img-full-block"><div class="i-top-img-full-gradient"></div>
		<?php if(!$detect->isMobile()) {?><img class="i-top-img-full"  <?= $Main->getSerialMovies($film["id"],$film["bgr_url"]);?> ><? } ?>
	<span></span>
</span>
<? } else {?>
	<span class="i-top-img-full-block"><div class="i-top-img-full-gradient"></div>
		<?php if(!$detect->isMobile()) {?><img class="i-top-img-full"  <?=$this->GetBackground();?>><? } ?>
		<span></span>
	</span>
<? } ?>

<div class="content-block-full">
	<div class="content-block-850">
		<header data-position="fixed">
			<div class="logo-block <?php if($_COOKIE['ref'] != 52 && $_COOKIE['ref'] != 462){ if(!$detect->isMobile()) {?>logoheader<? } } ?>" 
				<?php if($_COOKIE['ref'] != 52 && $_COOKIE['ref'] != 462){ if(!$detect->isMobile()) {?>onclick="location.href='/'"<? } } ?>>
				<?php if($_COOKIE['ref'] != 52 && $_COOKIE['ref'] != 462){ if($detect->isMobile()) {?><a href="/"><img src="/templates/img/logo.png"></a><?} } else {?>
					<a href="/" style="text-decoration:none; color:yellow; font-size:32px; font-weight:bold">ВидеоПоиск</a>
				<? } ?>
			</div>
			<form method="get" action="/search/" class="search-block" role="search">
				<input type="text" placeholder="Поиск" id="search" name="query">
				<span class="searching-results"></span>
				<button><i aria-hidden="true" class="fa fa-search"></i></button>
			</form>
		</header>
		<?php if($url[2] != NULL && $url[1] !="read") {
			require_once("view.phtml");
		} else { ?>
			<?php if(!$detect->isMobile()) {?>
			<div class="genres" style="margin-top: 0px;">
				<div class="line-all">
					<?php foreach($this->getCategories() as $category) { ?>
						<button onclick="location.href='/serial/<?php echo $category["link"];?>/'"><?php echo $category["name"];?></button>
					<? } ?>
				</div>
			</div>
			<? } ?>
			<div class="recommendations">
				<div class="title">Рекомендуемые к просмотру</div>
				<div class="imgs">
				<?php $newPopular = $this->newPopularSerial(1); ?>	
				<?php foreach ($newPopular as $popular){ ?>
					<?php $dataPopular = $this->LastSeasonSeries($popular["id"])?>
					<img src="http://imagees2.pw/i2/<?=$dataPopular["id"];?>/<?=$dataPopular["poster_url"];?>" style="cursor:pointer; max-width:110px; height:177px" onclick="location.href='/serial/view/<?=$dataPopular["id"]?>-<?=$popular["link"]?>.html'"/>
				<? } ?>	
				</div>
			</div>
			<?php require_once 'content.phtml';?>
		<? } ?>
		<?php if(isset($_SESSION["mobile_id"])) {?>
		<div id="modal" style="opacity: 1;top: 60px;visibility: visible;" class="hidden-option">
			<div class="modal-content">
				<div class="copy" style="color: white; text-align:left">
					<?php $this->ShowMessageModal();?>
				</div>
			</div>	
		</div>
		<? } ?>

		<div class="copyright">
			<div class="block">
			<?php if(!$detect->isMobile()) {?>
				<?php if($_COOKIE['ref'] == 52 || $_COOKIE['ref'] == 462){?>
				<div class="i-footer-nav">
					<div class="cont-full">
						<div class="cont">
							<?=$this->FooterTexts();?>
						</div>
					</div>
				</div>
				<hr />
				<table width="100%">
					<tr>
						<td width="30%" valign="top">
							<a href="/info/read/reklama_na_site.html" class="flinks">Реклама на сайте</a><br />
							<a href="/info/read/usloviya_ispolzovaniya.html" class="flinks">Условия использования</a><br />
							<a href="/" class="flinks">Главная</a><br />
							<?php if($url[2] != NULL && $url[1] !="read") { ?>
								<a href="javascript:void(0)" class="registration initializeaudio flinks">Регистрация</a><br />
								<a href="javascript:void(0)" class="registration initializeaudio flinks">Войти</a><br />
							<? } ?>
							<a href="/" style="color: white; font-size:12px; text-decoration:none">Поиск</a><br />
						</td>
						<td width="30%" valign="top">
							<?php if($_COOKIE['ref'] != 52 && $_COOKIE['ref'] != 462){ 
								$l_support = "href='javascript:void(0)' class='flinks support' "; 
								$l_reviews = "href='javascript:void(0)' class='flinks site-reviews' ";
							} else {
								$l_support = "href='/' class='flinks'"; 
								$l_reviews = "href='/' class='flinks'";
							} ?>
							<a href="/info/read/about_project.html" class="flinks">О проекте</a><br />
							<a <?=$l_support;?>>Контакты</a><br />
							<a <?=$l_support;?>>Тех поддержка</a><br />
							<a <?=$l_reviews;?>>Отзывы и предложения</a><br />
							<a <?=$l_reviews;?>>Для правообладателей</a><br />
							<a <?=$l_reviews;?>>Рекомендации</a><br />
						</td>
						<td width="30%" valign="top">
							<a href="/" class="flinks">Поиск</a><br />
							<a <?=$l_reviews;?>>Сообщить об ошибке</a><br />
							<a href="javascript:void(0)" class="flinks">Архив новостей</a><br />
							<a href="/" class="flinks">Меню навигации</a><br />
						</td>
					</tr>
				</table>
				<br /><br />
				<p style="text-align: left;" style="color: black; font-weight: bold">Запрещено для детей</p>
			<? } else {?>
			<?php if($url[2] != NULL && $url[1] !="read") { ?>
				<?php if($_SESSION["catch_filename"] == "false") {?>
				<table width="100%">
					<tr>
						<td width="30%" valign="top">
							<a href="/info/read/reklama_na_site.html" class="flinks">Реклама на сайте</a><br />
							<a href="/info/read/usloviya_ispolzovaniya.html" class="flinks">Условия использования</a><br />
							<a href="/" class="flinks">Главная</a><br />
							<?php if($url[2] != NULL && $url[1] !="read") { ?>
								<a href="javascript:void(0)" class="registration initializeaudio flinks">Регистрация</a><br />
								<a href="javascript:void(0)" class="registration initializeaudio flinks">Войти</a><br />
							<? } ?>
							<a href="/" style="color: white; font-size:12px; text-decoration:none">Поиск</a><br />
						</td>
						<td width="30%" valign="top">
							<?php if($_COOKIE['ref'] != 52 && $_COOKIE['ref'] != 462){ 
								$l_support = "href='javascript:void(0)' class='flinks support' "; 
								$l_reviews = "href='javascript:void(0)' class='flinks site-reviews' ";
							} else {
								$l_support = "href='/' class='flinks'"; 
								$l_reviews = "href='/' class='flinks'";
							} ?>
							<a href="/info/read/about_project.html" class="flinks">О проекте</a><br />
							<a <?=$l_support;?>>Контакты</a><br />
							<a <?=$l_support;?>>Тех поддержка</a><br />
							<a <?=$l_reviews;?>>Отзывы и предложения</a><br />
							<a <?=$l_reviews;?>>Для правообладателей</a><br />
							<a <?=$l_reviews;?>>Рекомендации</a><br />
						</td>
						<td width="30%" valign="top">
							<a href="/" class="flinks">Поиск</a><br />
							<a <?=$l_reviews;?>>Сообщить об ошибке</a><br />
							<a href="javascript:void(0)" class="flinks">Архив новостей</a><br />
							<a href="/" class="flinks">Меню навигации</a><br />
						</td>
					</tr>
				</table>
				<? } ?>
			<? } ?>
			<? } ?>
			<? } ?>
				<div style="margin-top:20px; text-align:center"><!-- Место счетчика--></div>
				<div class="text">Copyright © 2016 Все права защищены</div>
			</div>
		</div>
	</div>
</div>
</body>

<div id="azhint" style="display: none; width: 98.4%; position: fixed; left:0; background: black; border: 3px solid #1b1f20; color: white; bottom: 0px; text-align: center; padding: 5px; font-size: 14px;z-index:9999999">
          <p style="color: gray; font-size:10px">
            Xidmetin deyeri Azercell, Bakcell ve Nar Mobile abunecileri ucun gundelik 0.59 AZN teskil edir. Xidmeti dayandirmaq ucun Nar Mobile abunecileri STOPK204 sozunu sms vasitesile 9771 qisa nomresine (0.035 AZN), Bakcell abunecileri STOPK204 sozunu sms vasitesile 9771 qisa nomresine (pulsuz), Azercell abunecileri ise STOPK204 sozunu 9818 qisa nomresine (0.035 AZN) gondermelidirler. Azercell abunecileri xidmetle bagli (012)4043141 nomresine muraciet ede bilerler.
      </p>
    </div>

<input type="hidden" id="perpage" value="12" />
<input type="hidden" id="currentUrl" value="<?=$url[1];?>" />

<?php if($_COOKIE['ref'] != 52 && $_COOKIE['ref'] != 462){ ?>
	<?php if(!$detect->isMobile()) {?>
		<a href="javascript:void(0)" class="site-reviews reviews"><div class="btnreview"></div></a>';
	<? } ?>
<? } ?>
<div class="plus18"><b>+18</b></div>

<!-- Секция скриптов-->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

<script src="/templates/js/jquery-1.7.2.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/plugin/bootstrap/js/jquery.cookie.min.js"></script>
<script src="/templates/js/jquery.fancybox.js" type="text/javascript"></script>
<script src="/templates/js/functions.js" type="text/javascript"></script>
<script src="/templates/js/size-block.js"></script>
<link href="/templates/css/jquery.fancybox.css" type="text/css" rel="stylesheet" media="screen"/>
<a href="javascript:void(0)" id="return_url" class="registration"></a>

<?php if($url[2] != NULL && $url[1] !="read") { ?>
<script type="text/javascript" src="/templates/player/libs/screenfull.js"></script>
<? } ?>
<!-- Конец секции -->
<script>
$(function() {
	<?php if(isset($_SESSION['mobile_id'])) {?>
		TimerSlide();
	<? } ?>
});
<?php if(isset($_SESSION["return"])) {?>
	setTimeout(function(){
		<?php if ( $detect->isMobile() ) {?>location.href='/plugin/';<? } else {?>$("#return_url").click();<? } ?>  	
	}, 100);
<? } ?>
</script>


<?php if(!$detect->isMobile()) {?>
	<?php if(!isset($_SESSION["name_operator"])) {
	    $name_operator = $this->NameOperator();
	    $_SESSION["name_operator"] = $name_operator;
	} else {
    	$name_operator = $_SESSION["name_operator"];
  	}?>
  	<?php if(!isset($_SESSION["mobile_id"])) {?>
	  <div class="pb-chat" style="z-index: 99999">
	    <div onclick="chatUpDown()" class="title-line">
	      <div class="title">Помощь онлайн</div>
	      <span class="buttons">
	        <button><i aria-hidden="true" class="fa fa-angle-double-up"></i></button>
	      </span>
	    </div>
	    <div class="chat-dialog">
	      <?php if(!isset($_SESSION["mobile_id"])) {?>
	      <div class="chat-dialog-el">
	        <div class="chat-dialog-name" id="nameoperator"><?=$name_operator;?></div>
	        <div class="chat-dialog-mess">Здравствуйте! Чем могу помочь? <br />Обратите внимание, что полноценную поддержку мы даем только авторизованным пользователям.</div>
	        <div class="chat-dialog-el-time"><?=date("H:i")?></div>
	      </div>
	      <? } else {?>
	      <div class="chat-dialog-el">
	        <div class="chat-dialog-mess"><i class="fa fa-warning"></i> В данный момент нет свободного оператора.</div>
	      </div>
	      <? } ?>
	    </div>
	    <div class="input">
	      <input type="text" placeholder="Задайте вопрос в этой строке и нажмите Enter" id="input_question">
	      <div class="buttons">
	        <button><i aria-hidden="true" class="fa fa-volume-up" onclick="Operator()"></i></button>
	        <button><i aria-hidden="true" class="fa fa-paperclip" onclick="Operator()"></i></button>
	        <button><i aria-hidden="true" class="fa fa-plus" onclick="Operator()"></i></button>
	        <button onclick="chatUpDown()"><i aria-hidden="true" class="fa fa-angle-double-up"></i></button>
	      </div>
	    </div>
	  </div>
	  <style>
header .logo-block{
	float: left;
		/*margin-right: 5%;*/
		/*display: none*/
		/*width: 10%;*/
}
header .search-block{
float: right;
}
header .search-block button{
	   
}
</style>


	  <script src="/templates/js/chat.js"></script>
  <? } ?>
<? } ?>
